routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('pages.home');
// });

Route::get('/', 'PageController@halamanDepan')->name('halamanDepan');
Route::get('/sukses/{message}', 'PageController@sukses')->name('sukses');

Auth::routes();

Route::group(['prefix' => 'register', 'as' => 'register.'], function () {
    Route::get('/daftar', 'Auth\RegisterController@pilihRole')->name('pilihRole');
    Route::get('/daftar/{role}', 'Auth\RegisterController@formulir')->name('formulir');
});

Route::group(['prefix' => 'toko', 'as' => 'toko.'], function () {
    Route::get('/', 'TokoController@cari')->name('cari');
    Route::get('/kategori/{kategori}', 'TokoController@cariKategori')->name('cari.kategori');
    Route::get('/pencarian/{keyword}', 'TokoController@cariKeyword')->name('cari.keyword');
    Route::get('/urutkan/{kategori}/{urutan}', 'TokoController@cariUrutkan')->name('cari.urutkan');
    Route::post('/tukar/{barang}', 'TokoController@tukar')->name('tukar');
});

Route::group(['prefix' => 'relawan', 'as' => 'relawan.'], function () {
    Route::get('/', 'RelawanController@tentang')->name('tentang');
    Route::get('/formulir', 'RelawanController@formulir')->name('formulir');
    Route::post('/daftar', 'RelawanController@daftar')->name('daftar');
});

Route::group(['prefix' => 'donasi', 'as' => 'donasi.'], function () {
    Route::get('/formulir/barang', 'DonasiController@formulirBarang')->name('formulir.barang');
    Route::get('/formulir/makanan', 'DonasiController@formulirMakanan')->name('formulir.makanan');
    Route::post('/submit/barang', 'DonasiController@submitBarang')->name('submit.barang');
    Route::post('/submit/makanan', 'DonasiController@submitMakanan')->name('submit.makanan');
});

Route::group(['prefix' => 'usul', 'as' => 'usul.'], function () {
    Route::get('/formulir', 'UsulController@formulir')->name('formulir');
    Route::post('/submit', 'UsulController@submit')->name('submit');
});

Route::get('/sukses-belanja', function () {
     return view('pages.suksesbelanja');
 });

// Route::get('/donasi', 'PageController@donasi')->name('donasi');
// Route::get('/relawan', 'PageController@relawan')->name('relawan');

// Route::get('/donasi-pangan', function () {
//     return view('pages.donasipangan');
// });
//
// Route::get('/donasi-barang', function () {
//     return view('pages.donasibarang');
// });
//
// Route::get('/toko', function () {
//     return view('pages.toko');
// });
//
// Route::get('/relawan', function () {
//     return view('pages.relawan');
// });
//
// Route::get('/usulan-penerima', function () {
//     return view('pages.usulanpenerima');
// });

// Route::get('/home', 'HomeController@index')->name('home');

Route::get('/usul-penerima', function () {
    return view('pages.usulpenerima');
});

Route::get('/registrasi-penerima', function () {
    return view('pages.registrasipenerima');
});

Route::get('/registrasi-donatur', function () {
    return view('pages.registrasidonatur');
});

Route::get('/loginn', function () {
    return view('pages.login');
});

//
//
// Auth::routes();
//
// Route::get('/home', 'HomeController@index')->name('home');

resources/views/pages/daftarrelawan.blade.php
@extends('layouts/base')

@section('title', 'Daftar Relawan')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')

<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
            <img class="full-img" src="{{ asset('img/relawan.png')}}">
		</div>
		<div class="col-md-6 white-panel" >
			<h2 class="text-center font-weight-bold">
				Daftar menjadi Relawan
			</h2>

			<form method="POST" action="{{ route('relawan.daftar') }}">
				@csrf
				<div class="form-group">
					<label for="inputJenisPangan">
						Nama lengkap
					</label>
					<input name="name" required focus type="text" class="form-control @error('name') is-invalid @enderror" id="inputJenisPangan" value="{{ old('name') }}" autocomplete="name" placeholder="Bernard Jones">
					@error('name')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
				<div class="form-group">
					<label for="inputJumlahPorsi">
						Nomor telepon
					</label>
					<input required type="tel" class="form-control @error('telepon') is-invalid @enderror" name="telepon" id="inputJumlahPorsi" value="{{ old('telepon') }}" placeholder="(239) 555-0108">
					@error('telepon')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
                <div class="form-group">
					<label for="inputKadaluarsa">
						Alamat
					</label>
					<input name="alamat" required type="text" class="form-control" id="inputKadaluarsa" placeholder="Jl Margonda Raya No 71">
					@error('alamat')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
                <div class="form-group">
					<label for="inputKeterangan">
						Email
					</label>
					<input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" id="inputKeterangan" placeholder="john@doe.com" autocomplete="email">
					@error('email')
						<span class="invalid-feedback" role="alert">
							<strong>{{ $message }}</strong>
						</span>
					@enderror
				</div>
				<div>
					<label class="container">Dengan ini, saya menyatakan data yang saya isi adalah benar dan valid
  					<input type="checkbox" required>
  					<span class="checkmark"></span>
					</label>
				</div>
                <div class="button-group">
                    <button type="button" class="secondary-btn large-btn" onclick="location.href='{{ URL::previous() }}'">KEMBALI</button>
                    <button type="submit" class="primary-btn large-btn">DAFTAR</button>
                </div>
			</form>
		</div>
	</div>
</div>
@endsection

@section('extra-js')

@endsection

resources/views/pages/donasiMakanan.blade.php
@extends('layouts/base')

@section('title', 'Platform Berbagi Bersama')

@section('extra-fonts')

@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')
    <div>
        Formulir Donasi Makanan
    </div>
@endsection

@section('extra-js')

@endsection

resources/views/pages/donasibarang.blade.php
@extends('layouts/base')

@section('title', 'Donasi Barang')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')


<div class="container-fluid">
	<form method="POST" action="{{ route('donasi.submit.barang') }}">
		@csrf
	<div class="row">
		<div class="col-md-6">
            <img class="full-img" src="{{ asset('img/donasibarang.png')}}">
		</div>

		<div class="col-md-6 white-panel tab" >
			<h2 class="text-center font-weight-bold">
				Detail Donasi
			</h2>
	        <img style="width:200px; margin-left: 25%; margin-right: 25%;"src="{{ asset('img/progress1.png')}}">
	        <br><br>

			<div class="form-group">
				<label for="inputJenisPangan">
					Jenis barang
				</label>
				<input name="jenis" required focus type="text" class="form-control" id="inputJenisPangan" placeholder="Baju dan celana bekas">
			</div>
			<div class="form-group">
				<label for="inputJumlahPorsi">
					Jumlah barang
				</label>
				<input name="jumlah" required type="number" class="form-control" id="inputJumlahPorsi" placeholder="14 pcs">
            </div>
            <div class="form-group">
				<label for="inputKadaluarsa">
					Keterangan tambahan (opsional)
				</label>
				<input name="keterangan" required type="text" class="form-control" id="inputKadaluarsa" placeholder="Pakaian bekas dewasa">
            </div>
			<div style="height: 78px" class="white-space"></div>
            <div class="button-group">
                <button type="button" class="secondary-btn large-btn" onclick="location.href='{{ URL::previous() }}'">BATAL</button>
                <button type="button" class="primary-btn large-btn" onclick="nextPrev(1)">LANJUT</button>
            </div>
		</div>

		<div class="col-md-6 white-panel tab">
			<h2 class="text-center font-weight-bold">
				Data Donatur
			</h2>
            <img style="width:200px; margin-left: 25%; margin-right: 25%;"src="{{ asset('img/progress2.png')}}">
            <br><br>

			<div class="form-group">
				<label for="inputJenisPangan">
					Nama donatur
				</label>
				<input name="nama_donatur" value="{{ $user->name }}" required focus type="text" class="form-control" id="inputJenisPangan" placeholder="John Doe">
			</div>
			<div class="form-group">
				<label for="inputJumlahPorsi">
					Nomor telepon
				</label>
				<input name="telepon" value="{{ $user->telepon }}" required type="tel" class="form-control" id="inputJumlahPorsi" placeholder="0878123456789">
            </div>
            <div class="form-group">
				<label for="inputKadaluarsa">
					Alamat
				</label>
				<input name="alamat" value="{{ $user->alamat }}" required type="text" class="form-control" id="inputKadaluarsa" placeholder="Jl Sudirman No. 250 Jakarta">
            </div>
            <div class="form-group">
				<label for="inputKeterangan">
					Email
				</label>
				<input name="email" value="{{ $user->email }}" type="email" class="form-control" id="inputKeterangan" placeholder="john@doe.com">
			</div>

			<div>
				<label class="container">Dengan ini, saya menyatakan data yang saya isi adalah benar dan valid
					<input type="checkbox" required>
					<span class="checkmark"></span>
				</label>
			</div>

            <div class="button-group">
                <button type="button" class="secondary-btn large-btn" onclick="prevNext(1)">KEMBALI</button>
                <button type="submit" class="primary-btn large-btn">KIRIM</button>
            </div>
		</div>

	</div>
	</form>
</div>
@endsection

@section('extra-js')
	<script type="text/javascript">
		var currentTab = 0; // Current tab is set to be the first tab (0)
		(document.getElementsByClassName("tab"))[currentTab].style.transform = "scale(1,1)";
		(document.getElementsByClassName("tab"))[currentTab].style.height = "100%";
		function nextPrev(n) {
			var x = document.getElementsByClassName("tab");
			if (n == 1) {
				x[currentTab].style.display = "none";
				currentTab += n;
				console.log(currentTab);
				x[currentTab].style.display = "block";
				x[currentTab].style.transform = "scale(1,1)";
				x[currentTab].style.height = "100%";
			}
		}
		function prevNext(n) {
			var x = document.getElementsByClassName("tab");
			if (n == 1) {
				x[currentTab].style.display = "none";
				currentTab -= n;
				console.log(currentTab);
				x[currentTab].style.display = "block";
				x[currentTab].style.transform = "scale(1,1)";
				x[currentTab].style.height = "100%";
			}
		}
	</script>
@endsection

resources/views/pages/donasibarang2.blade.php
@extends('layouts/base')

@section('title', 'Donasi Pangan')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')


<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
            <img class="full-img" src="{{ asset('img/donasibarang.png')}}">
		</div>
		<div class="col-md-6 white-panel" >
			<h2 class="text-center font-weight-bold">
				Data Donatur
			</h2>
            <img style="width:200px; margin-left: 25%; margin-right: 25%;"src="{{ asset('img/progress2.png')}}">
            <br><br>
             
			<form role="form">
				<div class="form-group">
					<label for="inputJenisPangan">
						Nama donatur
					</label>
					<input required focus type="text" class="form-control" id="inputJenisPangan" placeholder="John Doe">
				</div>
				<div class="form-group">
					<label for="inputJumlahPorsi">
						Nomor telepon
					</label>
					<input required type="text" class="form-control" id="inputJumlahPorsi" placeholder="0878123456789">
                </div>
                <div class="form-group">
					<label for="inputKadaluarsa">
						Alamat
					</label>
					<input required type="date" class="form-control" id="inputKadaluarsa" placeholder="Jl Sudirman No. 250 Jakarta">
                </div>
                <div class="form-group">
					<label for="inputKeterangan">
						Email
					</label>
					<input type="textarea" class="form-control" id="inputKeterangan" placeholder="john@doe.com">
				</div>

				<div>
					<label class="container">Dengan ini, saya menyatakan data yang saya isi adalah benar dan valid
  					<input type="checkbox">
  					<span class="checkmark"></span>
					</label>
				</div>
				
                <div class="button-group">
                    <button type="button" class="secondary-btn large-btn">KEMBALI</button>
                    <button type="button" class="primary-btn large-btn">KIRIM</button>
                </div>
			</form>
		</div>
	</div>
</div>
@endsection

@section('extra-js')

@endsection

resources/views/pages/donasipangan.blade.php
@extends('layouts/base')

@section('title', 'Donasi Pangan')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')


<div class="container-fluid">
	<form method="POST" action="{{ route('donasi.submit.barang') }}">
		@csrf
	<div class="row">
		<div class="col-md-6">
            <img class="full-img" src="{{ asset('img/donasipangan.png')}}">
		</div>

		<div class="col-md-6 white-panel tab">
			<h2 class="text-center font-weight-bold">
				Detail Donasi
			</h2>
            <img style="width:200px; margin-left: 25%; margin-right: 25%;"src="{{ asset('img/progress1.png')}}">
            <br><br>
			<div class="form-group">
				<label for="inputJenisPangan">
					Jenis pangan
				</label>
				<input name="jenis" required focus type="text" class="form-control" id="inputJenisPangan" placeholder="Nasi kotak, beras, makanan kaleng, dsb">
			</div>
			<div class="form-group">
				<label for="inputJumlahPorsi">
					Jumlah porsi / ukuran
				</label>
				<input name="jumlah" required type="number" class="form-control" id="inputJumlahPorsi" placeholder="50 kotak, 100 liter, 30 pcs dsb">
            </div>
            <div class="form-group">
				<label for="inputKadaluarsa">
					Estimasi tanggal kadaluarsa
				</label>
				<input name="kadaluarsa" required type="date" class="form-control" id="inputKadaluarsa" placeholder="Nasi kotak, beras, makanan kaleng, dsb">
            </div>
            <div class="form-group">
				<label for="inputKeterangan">
					Keterangan tambahan (opsional)
				</label>
				<input name="keterangan" type="text" class="form-control" id="inputKeterangan" placeholder="Keterangan tambahan...">
			</div>

            <div class="button-group">
                <button type="button" class="secondary-btn large-btn" onclick="location.href='{{ URL::previous() }}'">BATAL</button>
                <button type="button" class="primary-btn large-btn" onclick="nextPrev(1)">LANJUT</button>
            </div>
		</div>

		<div class="col-md-6 white-panel tab" >
			<h2 class="text-center font-weight-bold">
				Data Donatur
			</h2>
			<img style="width:200px; margin-left: 25%; margin-right: 25%;"src="{{ asset('img/progress2.png')}}">
			<br><br>

			<div class="form-group">
				<label for="inputJenisPangan">
					Nama donatur
				</label>
				<input name="nama_donatur" value="{{ $user->name }}" required focus type="text" class="form-control" id="inputJenisPangan" placeholder="John Doe">
			</div>
			<div class="form-group">
				<label for="inputJumlahPorsi">
					Nomor telepon
				</label>
				<input name="telepon" value="{{ $user->telepon }}" required type="tel" class="form-control" id="inputJumlahPorsi" placeholder="0878123456789">
			</div>
			<div class="form-group">
				<label for="inputKadaluarsa">
					Alamat
				</label>
				<input name="alamat" value="{{ $user->alamat }}" required type="text" class="form-control" id="inputKadaluarsa" placeholder="Jl Sudirman No. 250 Jakarta">
			</div>
			<div class="form-group">
				<label for="inputKeterangan">
					Email
				</label>
				<input name="email" value="{{ $user->email }}" type="email" class="form-control" id="inputKeterangan" placeholder="john@doe.com">
			</div>

			<div>
				<label class="container">Dengan ini, saya menyatakan data yang saya isi adalah benar dan valid
				<input type="checkbox" required>
				<span class="checkmark"></span>
				</label>
			</div>

			<div class="button-group">
				<button type="button" class="secondary-btn large-btn" onclick="prevNext(1)">KEMBALI</button>
				<button type="submit" class="primary-btn large-btn">KIRIM</button>
			</div>
		</div>

	</div>
	</form>
</div>
@endsection

@section('extra-js')
	<script type="text/javascript">
		var currentTab = 0; // Current tab is set to be the first tab (0)
		(document.getElementsByClassName("tab"))[currentTab].style.transform = "scale(1,1)";
		(document.getElementsByClassName("tab"))[currentTab].style.height = "100%";
		function nextPrev(n) {
			var x = document.getElementsByClassName("tab");
			if (n == 1) {
				x[currentTab].style.display = "none";
				currentTab += n;
				console.log(currentTab);
				x[currentTab].style.display = "block";
				x[currentTab].style.transform = "scale(1,1)";
				x[currentTab].style.height = "100%";
			}
		}
		function prevNext(n) {
			var x = document.getElementsByClassName("tab");
			if (n == 1) {
				x[currentTab].style.display = "none";
				currentTab -= n;
				console.log(currentTab);
				x[currentTab].style.display = "block";
				x[currentTab].style.transform = "scale(1,1)";
				x[currentTab].style.height = "100%";
			}
		}
	</script>
@endsection

resources/views/pages/home.blade.php
@extends('layouts/base')

@section('title', 'Platform Berbagi Bersama')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h1>
				MUSE.ID
			</h1>
			<p style="width: 700px">
				<b>MUSE.ID</b> membantu pengguna untuk mendonasikan barang dan pangan berlebih yang mereka miliki, serta dengan serangkaian uji kelayakan makanan untuk disalurkan pada masyarakat pra-sejahtera (kaum dhuafa, yatim piatu, janda, lansia, difabel, pengungsi, dan anak jalanan) di Jakarta.			</p>
		</div>
	</div>

	<div style="height: 48px" class="white-space"></div>
	<div class="row">
		<div class="col-md-4">
			<div style="height: 410px" class="card">
				<div class="card-body">
				<img class="full-img" src="{{ asset('img/card1.png')}}">
				<br><br>
				<h4>Donasi Pangan</h4>
					<p>
					Donasikan bahan pangan atau makanan berlebih yang kamu ingin kamu bagikan.
					</p>
					<button onclick="location.href='{{ route('donasi.formulir.makanan') }}'" class="primary-btn med-btn right-btn">DONASI</button>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div style="height: 410px" class="card">
				<div class="card-body">
				<img class="full-img" src="{{ asset('img/card2.png')}}">
				<br><br>
				<h4>Donasi Barang</h4>
					<p>
					Donasikan barang layak pakai, yang sudah tidak kamu gunakan, seperti pakaian, buku, furnitur, koran, dll.					</p>
					<button onclick="location.href='{{ route('donasi.formulir.barang') }}'" class="primary-btn med-btn right-btn">DONASI</button>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div style="height: 410px" class="card">
				<div class="card-body">
				<img class="full-img" src="{{ asset('img/card3.png')}}">
				<br><br>
				<h4>Toko Barang</h4>
					<p style="color: #233B6E; font-size:13px; margin-top: -10px;">(Khusus pemilik Kartu Keluarga Sejahtera) </p>
					<p style="margin-top: -15px;">
					Dapatkan pilihan barang gratis dengan menukarkan poin yang kamu miliki.					</p>
					<button onclick="location.href='{{ route('toko.cari') }}'" class="primary-btn med-btn right-btn">KUNJUNGI</button>
				</div>
			</div>
		</div>
	</div>

	<div class="white-space"></div>

	<div class="row">
		<div class="col-md-4">
			<img style="width: 300px;" src="{{ asset('img/home1.png')}}">
		</div>
		<div class="col-md-8 pl-5">
			<h2>
				Tentang Kami
			</h2>
			<br>
			<p style="width: 500px;">
			Muse.id didirikan pada tahun 2019 oleh tiga orang pemuda dengan memiliki visi untuk meningkatkan kesejahteraan masyarakat Jakarta, terutama masyarakat pra-sejahtera yang belum memiliki akses untuk mencukupi kebutuhan sandang, pangan, dan papan mereka dengan mudah. Muse.id bertujuan meminimalkan dan membantu menurunkan tingkat kemiskinan masyarakat Jakarta, serta menumbukan empati kepada masyarakat yang sudah berkecukupan untuk saling berbagi kepada sesama.			</p>

		</div>
	</div>

	<div class="white-space"></div>

	<div class="row">
		<div class="col-md-6">
		<div class="white-space"></div>

			<h2>
				Relawan MUSE.ID
			</h2>
			<br>
			<p><b>#AyoJadiMuseHeroes</b><br>
			Dengan menjadi relawan, dapatkan pengalaman berharga untuk membantu Muse.id menjemput barang donasi dari donatur dan menyalurkan donasi yang sudah diberikan kepada masyarakat pra-sejahtera di Jakarta.
			<br><br>
			<button onclick="location.href='{{ route('relawan.tentang') }}'" class="primary-btn large-btn">DAFTAR</button>

			</div>
		<div class="col-md-6 pl-5">
			<img style="height: 500px;" src="{{ asset('img/home2.png')}}">
		</div>
	</div>

	<div class="white-space"></div>


	<div class="row">
		<div class="col-md-5">
			<img style="width: 400px;" src="{{ asset('img/home3.png')}}">
		</div>
		<div class="col-md-7 pl-5">
			<h2>
				Usulkan Penerima
			</h2>
			<br>
			<p clas="pl-5" style="width: 500px;">
			Bantu kami menyalurkan donasi yang Muse.id terima kepada cakupan masyarakat pra-sejahtera yang lebih luas di Jakarta, dengan cara memberikan rekomendasi masyarakat pra-sejahtera atau lokasi  yang membutuhkan bantuan. Usulan dan rekomendasi kamu akan sangat membantu Muse.id menyalurkan donasi dengan tepat sasaran.
			<br><br>
			<button onclick="location.href='{{ route('usul.formulir') }}'" style="width: 280px;" class="primary-btn large-btn">BERIKAN USUL</button>
		</div>
	</div>
</div>
@endsection

@section('extra-js')

@endsection

resources/views/pages/login.blade.php
@extends('layouts/base')

@section('title', 'Login')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')


<div class="container-fluid">

	<div class="row">

		<div class="col-md-6 register-panel" >
			<h2 class="text-center font-weight-bold">
				Login
			</h2>

			<form method="POST" action="{{ route('login') }}">
				@csrf
				<div class="form-group">
					<label for="inputJenisPangan">
						Email
					</label>
					<input type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" focus type="text" id="inputJenisPangan">
				</div>

				<div class="form-group">
					<label for="inputKeterangan">
						Password
					</label>
					<input type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password" id="inputKeterangan">
				</div>

                <button type="submit" class="primary-btn large-btn">LOGIN</button>

			</form>
		</div>
	</div>
</div>
@endsection

@section('extra-js')

@endsection

resources/views/pages/success.blade.php
@extends('layouts/base')

@section('title', 'Konfirmasi')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')


<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
            <div style="height: 450px; width: 500px; margin-left: auto; margin-right: auto" class="card p-4">
				<img style="width: 400px; margin-left: auto; margin-right: auto" src="{{ asset('img/success.png')}}">
                <br>
                <h5 class="text-center font-weight-bold">
                    {{ $message }}
                </h5>
                <br>
                <button  onclick="location.href='{{ route('halamanDepan') }}'" style="width: 250px; font-size: 12px;margin-left: auto; margin-right: auto" class="secondary-btn medium-btn">< Kembali ke home</button>
            </div>
        </div>
	</div>
</div>
@endsection

@section('extra-js')

@endsection

resources/views/pages/usulpenerima.blade.php
@extends('layouts/base')

@section('title', 'Usul Penerima')

@section('extra-fonts')
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet">
@endsection

@section('prerender-js')

@endsection

@section('extra-css')

@endsection

@section('content')

<div class="container-fluid">
	<form method="POST" action="{{ route('usul.submit') }}">
		@csrf
		<div class="row">
			<div class="col-md-6">
	            <img class="full-img" src="{{ asset('img/usul.png')}}">
			</div>
			<div class="col-md-6 white-panel" >
				<h2 class="text-center font-weight-bold">
					Usul Penerima
				</h2>

				<div class="form-group">
					<label for="inputJenisPangan">
						Nama lokasi
					</label>
					<input name="nama_lokasi" required focus type="text" class="form-control" id="inputJenisPangan" placeholder="Panti Asuhan Kasih Ibu">
				</div>
				<div class="form-group">
					<label for="inputJumlahPorsi">
						Alamat
					</label>
					<input nama="alamat" required type="text" class="form-control" id="inputJumlahPorsi" placeholder="Jl Sudirman No. 250 Jakarta">
                </div>
                <div class="form-group">
					<label for="inputKeterangan">
						Nama narahubung
					</label>
					<input name="nama_narahubung" type="text" class="form-control" id="inputKeterangan" placeholder="Brad Pitt">
				</div>
				<div class="form-group">
					<label for="inputKeterangan">
						Telepon
					</label>
					<input name="telepon" type="tel" class="form-control" id="inputKeterangan" placeholder="(239) 555-0108">
				</div>
				<div class="form-group">
					<label for="inputKeterangan">
						Perkiraan jumlah penerima
					</label>
					<input name="jumlah_penerima" type="number" class="form-control" id="inputKeterangan" placeholder="Sepuluh anak-anak">
				</div>
				<div class="form-group">
					<label for="inputKeterangan">
						Keterangan tambahan
					</label>
					<input name="keterangan" type="textarea" class="form-control" id="inputKeterangan" placeholder="Didekat daerah Kali Ciliwung">
				</div>
				<div>
					<label class="container">Dengan ini, saya menyatakan data yang saya isi adalah benar dan valid
  					<input type="checkbox" required>
  					<span class="checkmark"></span>
					</label>
				</div>
                <button type="submit" class="primary-btn large-btn">KIRIM</button>

			</div>
		</div>
	</form>
</div>
@endsection

@section('extra-js')

@endsection